project:
  type: website
  output-dir: docs

website:
  title: "Déployer avec un template _quarto.yml"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



